[tool.pytest.ini_options]
python_files = "test_*.py sentry/testutils/*"
addopts = "--tb=short --nomigrations -p no:celery -p no:cov"
markers = [
  "snuba: test requires access to snuba",
  "snuba_ci: test is run in snuba ci",
  "sentry_metrics: test requires access to sentry metrics",
  "symbolicator: test requires access to symbolicator",
]
filterwarnings = [
    # Consider all warnings to be errors other than the ignored ones.
    "error",
    "ignore:Marks applied to fixtures have no effect",
    "ignore:pkg_resources is deprecated as an API",
    "ignore:Deprecated call to `pkg_resources.declare_namespace\\('google.*'\\)`.",
    "ignore:Type google\\._upb.*",
    "ignore:.*sentry.digests.backends.dummy.DummyBackend.*:sentry.utils.warnings.UnsupportedBackend",
    "ignore:The --looponfail command line argument.*"
]
